### ISSUE TITLE
authClient.py needs to be updated

### ISSUE THREAD

**Issue by jacquesalice** [astro-datalab/datalab#74]
authClient.py needs to be updated from the authmanager repo. @chaduhduh can you do this? The version of this file in the authmanager repo only has docstrings updates

**Comment by chaduhduh** [comment]
Thanks for opening an issue @jacquesalice!

I am going to refactor how we handle the various duplicated client files so once I do that the issue should be resolved (I will start with auth). This will also be a good chance to test the new manual workflow since we will want to deploy the new version of the docs after this change is in place.
